language: java

jdk:
  - oraclejdk8

sudo: false # faster builds

notifications:
    slack: blossomproject:qUPz65E4R2K8KLnZ1wmVoXKb

after_success:
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
