server:
  port: 8090

initializr:
  versions:
    - blossom: 1.0.0-SNAPSHOT
      springboot: 1.5.4.RELEASE
  groups:
    - name: Core
      description: Blossom core functionalities
      dependencies:
        - name: Blossom Core
          id: blossom-starter-basic
          description: Blossom basic starter (no web interface)
          groupId: fr.blossom
          artifactId: blossom-starter-basic

    - name: Interfaces
      description: Blossom interfaces
      dependencies:
        - name: Blossom UI Web
          id: blossom-starter-ui-web
          description: Blossom UI Web starter (Back-office)
          groupId: fr.blossom
          artifactId: blossom-starter-ui-web
        - name: Blossom UI Api
          id: blossom-starter-ui-api
          description: Blossom UI Api starter (Back-office)
          groupId: fr.blossom
          artifactId: blossom-starter-ui-api
    - name: Miscellanous
      description: Blossom modules to add some functionnality in your application !
      dependencies:
        - name: Blossom File Manager
          id: blossom-starter-filemanager
          description: File storing and serving feature and tools
          groupId: fr.blossom
          artifactId: blossom-starter-filemanager
        - name: Blossom Articles
          id: blossom-starter-articles
          description: Richtext articles and front serving
          groupId: fr.blossom
          artifactId: blossom-starter-articles
